# This starter workflow is for a CMake project running on a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake for CIPF and SIPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build CIPF
      run: |
        cmake -B ${{github.workspace}}/CIPF/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/CIPF/build --config ${{env.BUILD_TYPE}}

    - name: Build SIPF
      run: |
        cmake -B ${{github.workspace}}/SIPF/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/SIPF/build --config ${{env.BUILD_TYPE}}
